adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    # path('users/create/', adminapp.user_create, name='user_create'),
    # path('users/read/', adminapp.users, name='users'),
    # path('users/update/<int:pk>', adminapp.user_update, name='user_update'),
    # path('users/delete/<int:pk>', adminapp.user_delete, name='user_delete'),
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UserListView.as_view(), name='users'),
    path('users/read/<int:page>/', adminapp.UserListView.as_view(), name='pg_users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),

    # path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    # path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    # path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    # path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    # path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductsAdminView.as_view(), name='products'),
    path('products/read/<int:pk>/', adminapp.ProductReadAdminView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateAdminView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteAdminView.as_view(), name='product_delete'),
]

authapp/urls.py
from django.urls import path, re_path
from . import views

app_name = 'authapp'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    re_path(
        r'^verify/(?P<email>.+)/(?P<activation_key>\w+)', 
        views.verify, 
        name='verify'
        ),
]

basketapp/urls.py
from django.urls import path
from . import views

app_name = 'basketapp'

urlpatterns = [
    path('', views.view, name='view'),
    path('add/<int:product_id>', views.add, name='add'),
    path('remove/<int:basket_item_id>/', views.remove, name='remove'),
    path('edit/<int:basket_item_id>/<int:quantity>/', views.edit_basket, name='edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
import authapp
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

import mainapp.views as mainapp  # mainapp =import_module('views', 'mainapp')
# from importlib import import_module


urlpatterns = [
    # Debug toolbar
    path('__debug__/', include(debug_toolbar.urls)),
    # social auth
    path('', include('social_django.urls', namespace='social')),
    # Application urls
    re_path(r'^auth/verify/google/oauth2', include('social_django.urls')),
    path('admin/', admin.site.urls),
    path('adminapp/', include('adminapp.urls', namespace='adminapp')),
    path('', mainapp.main, name='main'),
    path('contact/', mainapp.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    urlpatterns +=[path('__debug__/', include(debug_toolbar.urls)),]

# from debug_toolbar.panels.templates import panel

mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.products, name='all'),  # 'products'),
    path('<int:category_id>', views.category, name='category'),
    path('<int:category_id>/<int:page>', views.category, name='paged_cat'),
    path('product/<int:product_id>', views.product, name='product'),
    # path('/', mainapp.products, name='products'),
    # path('/<int:pk>', mainapp.category, name='category'),
]
# originally without slash

ordersapp/urls.py
from django.urls import path
import ordersapp.views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='orders_list'),
    path('forming/complete/<int:pk>',
    ordersapp.order_forming_complete, name='order_forming_complete'),
    path('create/', ordersapp.OrderCreate.as_view(), name='order_create'),
    path('read/<int:pk>', ordersapp.OrderDetail.as_view(), name='order_read'),
    path('update/<int:pk>', ordersapp.OrderUpdate.as_view(), name='order_update'),
    path('delete/<int:pk>', ordersapp.OrderDelete.as_view(), name='order_delete'),
    path('product/<int:pk>/price/', ordersapp.product_price, name=''),
]

urls.py
from django.contrib import admin
from django.urls import path, include, re_path
import authapp
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

import mainapp.views as mainapp  # mainapp =import_module('views', 'mainapp')
# from importlib import import_module


urlpatterns = [
    # social auth
    path('', include('social_django.urls', namespace='social')),
    # Debug toolbar
    path('__debug__/', include('debug_toolbar.urls')),
    # Application urls
    re_path(r'^auth/verify/google/oauth2', include('social_django.urls')),
    path('admin/', admin.site.urls),
    path('adminapp/', include('adminapp.urls', namespace='adminapp')),
    path('', mainapp.main, name='main'),
    path('contact/', mainapp.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
]

if settings.DEBUG:
    # import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    # urlpatterns +=[path('__debug__/', include(debug_toolbar.urls)),]

# from debug_toolbar.panels.templates import panel

mainapp/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import pre_save
# Create your models here.

class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=100)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='is active', default=True, db_index=True)
    def __str__(self):
        return self.name

class ProductManager(models.Manager):
    def active_items(self):
        return Product.objects.filter(is_active=True)

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя', max_length=100)
    price = models.DecimalField(verbose_name='цена', max_digits=7, decimal_places=2, default=0)
    color = models.CharField(verbose_name='цвет', default=0x000000, max_length=20)
    description = models.TextField(verbose_name='описание', blank=True)
    image = models.ImageField(verbose_name='картинка', blank=True, upload_to='products')
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)
    is_active = models.BooleanField(verbose_name='active object', default=True)

    objects = ProductManager()

    def __str__(self):
        return self.name


@receiver(pre_save, sender=ProductCategory)
def product_is_active_update_on_category_save(
    sender, update_fields, instance, **kwargs
):
    if instance.pk:
        instance.product_set.update(is_active=instance.is_active)
    # instance.product.save()

mainapp/views.py
import random
from django.core.cache import cache
from django.conf import settings
from functools import cached_property, lru_cache
from django.shortcuts import render, get_object_or_404
from django.views.decorators.cache import cache_page
from .models import Product, ProductCategory
from authapp.models import ShopUser
from django.core.paginator import Paginator, EmptyPage

# вариант кэширования списка продуктов
# список продуктов пересает меняться
def get_products():
    return Product.objects.all()[:4]

# Create your views here.
def main(request):
    # products = Product.objects.all()  # [:4]
    products = get_products()
    user = request.user
    # import pdb; pdb.set_trace()
    return render(request, 'mainapp/index.html',  context ={
        'title': 'Главная',
        'products': products,
        'user':user,
    })

@lru_cache
def get_hot_product(queryset):  #request, pk):
    # return random.choice(Product.objects.all())
    # if not queryset:
    #     return None
    # else:
        return random.choice(queryset)

def products(request):
    categories = ProductCategory.objects.all()
    products = Product.objects.all()  # [:4]
    # products = get_products()
    hot_product = None
    if products:
        hot_product = get_hot_product(products)
        products = products.exclude(pk=hot_product.pk)  #[:4]
    three_pics = [
        {'adr': 'controll.jpg',},
        {'adr': 'controll1.jpg',},
        {'adr': 'controll2.jpg',},
    ]
    return render(request, 'mainapp/products.html',  context ={
        'title': 'Продукты',
        'pics': three_pics,
        'categories': categories,
        'products': products,  # [:4]
        'hot_product': hot_product,
    })

@lru_cache
def get_prods(category_id):
    return Product.objects.filter(category_id=category_id)

def get_categories():
    # cache.get
    # cache.set
    if settings.LOW_CACHE:
        KEY = 'all_categories'
        categories = cache.get(KEY)
        if not categories:
            categories = ProductCategory.objects.all()
            cache.set(KEY, categories)
        return categories
    else:
        return ProductCategory.objects.all()

def category(request, category_id, page=1):
    # return products(request)
    # category = ProductCategory.objects().get(pk=pk)  # current category
    # categories = ProductCategory.objects.all()       # all categories
    categories = get_categories()
    category = get_object_or_404(ProductCategory, pk=category_id)
    # products = Product.objects.filter(category=category)
    products = get_prods(category_id)
    
    hot_product = None
    if products:
        hot_product = get_hot_product(products)
        products = products.exclude(pk=hot_product.pk)  #[:4]

    paginator = Paginator(products.exclude(pk=hot_product.pk), 3)
    try:
        products_page = paginator.page(page)
    except EmptyPage:
        products_page = paginator.page(paginator.num_pages)

    return render(
        request,
        "mainapp/products.html",
        context={
            "title": 'Prods', 
            'paginator': paginator,
            'page': products_page,
            # "products": paginator,# products.exclude(pk=hot_product.pk),  # [:4]
            "products": products_page,# products.exclude(pk=hot_product.pk),  # [:4]
            "categories": categories,
            'hot_product': hot_product,  # get_hot_product(products),
            'category':category,
        },
    )


def product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    categories = ProductCategory.objects.all()
    
    return render(
        request,
        'mainapp/product.html',
        context={
            'title': product.name,
            'product': product,
            'categories': categories,
        }
    )
    # return render(request, 'mainapp/product.html', context={
    #     'pk':pk,
    # })

# @cache_page(None)
def contact(request):
    return render(request, 'mainapp/contact.html',  context ={
        'title': 'Контакты',
    })

mainapp/templates/mainapp/includes/inc_categories_menu.html
{% load static %}
<div class="links clearfix">
    <ul class="links-menu">
        <li>
            <a href="{% url 'products:all' %}" 
                class="{% if request.resolver_match.view_name == 'products:all' %} active {% endif %}">all
            </a>
        </li>
        {% for category in categories %}
            <li>
                <a href="{% url 'products:category' category.id %}" 
                    class="{% if request.resolver_match.view_name == 'products:category' and request.resolver_match.kwargs.category_id == category.id %} 
                    active 
                    {% endif %}">
                    {{ category.name|title }}
                </a>
            </li>
        {% endfor %}
    </ul>
</div>

mainapp/templates/mainapp/includes/inc_main_menu.html
{% load static %}

<ul class="menu">
    
        {% comment %} <a href="{% url 'main' %}" class="logo"></a> {% endcomment %}
        <li><a href="/products">продукты</a></li>
        <li><a href="/contact">контакты</a></li> 
    
    {% for link in menu_links %}
        <li>
            <a href="{% url link.url %}" 
            {% comment %} {% if request.resolver_match.url_name == link.url %} {% endcomment %}
            {% if request.resolver_match.view_name in link.active %}
                class="active"
            {% endif%}
            >            
            {{ link.name }}
        </a>
        </li>
    {% endfor %}

    {% if user.is_authenticated %}
        <li>
            <div class="dropdown">
                <a class="dropdown-toggle" href="" data-toggle="dropdown">
                    {{ user.first_name|default:'DefaultUser' }}
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li class="dropdown-item">
                        <a href="{% url 'auth:edit' %}">
                            profile
                        </a>
                    </li>
                    <li class="dropdown-item">
                        <a href="{% url 'ordersapp:orders_list' %}">
                            orders
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        {% if user.is_superuser %}
            <li>
                <a href="{% url 'adminapp:users' %}">
                    Adminka
                </a>
            </li>        
        {% endif %}
        <li>
            <a href="{% url 'basket:view' %}">The_basket
                {% comment %} {% if user.basket.all|length %} ({{ user.basket.all|length }}) {% endif %} {% endcomment %}
                {% comment %} {% if user.basket.count %} ({{ user.basket.count }}) {% endif %} {% endcomment %}
                {{ user.basket.total_cost}} rub. ({{ user.basket.total_quantity }} pcs.)
            </a>
        </li>
    {% endif %}    
    {% comment "" %} enter/leave button {% endcomment %}
    <li>
        {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">leave</a>
        {% else %}
            <a href="{% url 'auth:login' %}">enter</a>
        {% endif %}
    </li>
</ul>
<a href="#" class="search"></a>
<a href="#" class="basket"></a>



mainapp/templates/mainapp/includes/inc_products.html
{% load static %}

{% if paginator %}
    {% if page.has_previous %}
        <a href="{% url 'products:paged_cat' category.id page.previous_page_number %}">Back</a>
    {% endif %}
    <h>Page {{ page.number }} of {{ paginator.num_pages }}</h>
    {% if page.has_next %}
        <a href="{% url 'products:paged_cat' category.id page.next_page_number %}">Forward</a>
    {% endif %}
{% endif %} 
{% for product in products %}
    <div class="block">
        {% with product_category=product.category %}
         <a href="{% url 'products:product' product.id %}"><img src="/media/{{ product.image }}" alt="">  {% comment %} здесь не хватало слэша в начале {% endcomment %}
            <div class="text" width="270" height="270">
                <img src="{% static "img/icon-hover.png" %}" alt="img">
                <h4>{{ product.destination }}</h4>
                <p>{{ product.description }}</p>
                <h5>{{ product_category }}</h5>
            </div>
        </a>
        {% endwith %}
    </div>
{% endfor %}

mainapp/templates/mainapp/includes/inc_second_menu.html
<div class="links clearfix">
    <ul class="links-menu">
        <!--<li><a href="#" class="active">все</a></li>
        тут хотел сделать с большой буквы; видимо, шрифты мешают-->
        {% comment %}{% for btn in ribbon_menu %} {% endcomment %}
        <li><a href="#" class="active">all</a></li>
        {% for btn in categories %}
        <li><a href="#">{{ btn|title }}</a></li>
        <!--<li><a href="#">{{ btn|capfirst }}</a></li>-->
        {% endfor %}
        {% comment %}<li><a href="#">офис</a></li>
        <li><a href="#">модерн</a></li>
        <li><a href="#">классика</a></li> {% endcomment %}
    </ul>
</div>