adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    # path('users/create/', adminapp.user_create, name='user_create'),
    # path('users/read/', adminapp.users, name='users'),
    # path('users/update/<int:pk>', adminapp.user_update, name='user_update'),
    # path('users/delete/<int:pk>', adminapp.user_delete, name='user_delete'),
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UserListView.as_view(), name='users'),
    path('users/read/<int:page>/', adminapp.UserListView.as_view(), name='pg_users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),

    # path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    # path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    # path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    # path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    # path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductsAdminView.as_view(), name='products'),
    path('products/read/<int:pk>/', adminapp.ProductReadAdminView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateAdminView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteAdminView.as_view(), name='product_delete'),
]

basketapp/urls.py
from django.urls import path
from . import views

app_name = 'basketapp'

urlpatterns = [
    path('', views.view, name='view'),
    path('add/<int:product_id>', views.add, name='add'),
    path('remove/<int:basket_item_id>/', views.remove, name='remove'),
    path('edit/<int:basket_item_id>/<int:quantity>/', views.edit_basket, name='edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
import authapp
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

import mainapp.views as mainapp  # mainapp =import_module('views', 'mainapp')
# from importlib import import_module


urlpatterns = [
    # Debug toolbar
    path('__debug__/', include(debug_toolbar.urls)),
    # social auth
    path('', include('social_django.urls', namespace='social')),
    # Application urls
    re_path(r'^auth/verify/google/oauth2', include('social_django.urls')),
    path('admin/', admin.site.urls),
    path('adminapp/', include('adminapp.urls', namespace='adminapp')),
    path('', mainapp.main, name='main'),
    path('contact/', mainapp.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    urlpatterns +=[path('__debug__/', include(debug_toolbar.urls)),]

# from debug_toolbar.panels.templates import panel

urls.py
from django.contrib import admin
from django.urls import path, include, re_path
import authapp
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

import mainapp.views as mainapp  # mainapp =import_module('views', 'mainapp')
# from importlib import import_module


urlpatterns = [
    # social auth
    path('', include('social_django.urls', namespace='social')),
    # Debug toolbar
    path('__debug__/', include('debug_toolbar.urls')),
    # Application urls
    re_path(r'^auth/verify/google/oauth2', include('social_django.urls')),
    path('admin/', admin.site.urls),
    path('adminapp/', include('adminapp.urls', namespace='adminapp')),
    path('', mainapp.main, name='main'),
    path('contact/', mainapp.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
]

if settings.DEBUG:
    # import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    # urlpatterns +=[path('__debug__/', include(debug_toolbar.urls)),]

# from debug_toolbar.panels.templates import panel

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import  forms
from authapp.forms import ShopUserEditForm, ShopUserRegisterForm
from mainapp.models import Product, ProductCategory
from authapp.models import ShopUser


class ShopUserEditAdminForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'

class ShopUserCreateAdminForm(ShopUserRegisterForm):
    class Meta:
        model = ShopUser
        fields = (
            'username',
            'first_name',
            # 'password',
            'email',
            'age',
            'avatar',
            'city',
            'phone',
        )

class ProductCategoryAdminForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'
    
    discount = forms.IntegerField(label='dscnt%', required=False, min_value=0, max_value=100)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


# class ProductCreateAdminForm(forms.ModelForm):
#     class Meta:
#         model = Product
#         fields = '__all__'

adminapp/views/category.py
from django.shortcuts import render, get_object_or_404
from mainapp.models import ProductCategory
from adminapp.forms import ProductCategoryAdminForm
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from django.db.models import F

def category_create(request):
    if request.method == 'POST':
        form = ProductCategoryAdminForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("adminapp:categories"))

    else:
        form = ProductCategoryAdminForm()
    return render(
        request,
        "adminapp/category/edit_c.html",
        context={'title':"create_category", 'form':form},
    )

    
def categories(request):
    categories = ProductCategory.objects.all().order_by('id')  # or .filter()

    return render(request, 'adminapp/category/categories.html', 
        context={
            'title': 'The_categories',
            'objects':categories,
        })

    
def category_update(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)
    if request.method == 'POST':
        form = ProductCategoryAdminForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            discount = form.cleaned_data.get('discount') or 0
            discounted_price = F('price') * (100 - discount) / 100
            category.product_set.update(price=discounted_price)
            return HttpResponseRedirect(reverse("adminapp:categories"))
    else:
        form = ProductCategoryAdminForm(instance=category)

    return render(
        request, 
        "adminapp/category/edit_c.html", 
        context={'title':"update_category", "form":form},
    )

    
def category_delete(request, pk):
    title = 'category'
    category = get_object_or_404(ProductCategory, pk=pk)
    if request.method == 'POST':
        # user.delete()
        # make inactive, not delete
        category.is_active = False
        category.save()
        return HttpResponseRedirect(reverse('admianpp:categories'))
    else:
        content = {'title':title, 'to_delete':category}
        return render(request, 'adminapp/category/delete_c.html', content)

adminapp/views/product.py
from django.shortcuts import render, get_object_or_404
# from adminapp.forms import ProductCreateAdminForm
from mainapp.models import Product, ProductCategory
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.utils.decorators import method_decorator
from adminapp.utils import superuser_required
from django.urls import reverse, reverse_lazy
from django.http.response import HttpResponseRedirect

# def product_create(request):
#     pass

class ProductCreateView(CreateView):
    model = Product
    # form_class = ProductCreateAdminForm
    template_name = 'adminapp/product/edit.html'
    fields = '__all__'
    # fields = (
    #     'category',
    #     'name',
    #     'price',
    #     'color',
    #     'description',
    #     'image',
    #     'quantity',
    # )

    @method_decorator(superuser_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    def get_initial(self):
        return {
            'category':self.get_category(),
        }

    def get_category(self):
        return ProductCategory.objects.get(pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.get_category()
        return context

    def get_success_url(self):
        return reverse("adminapp:products", kwargs=self.kwargs)


# path('products/read/category/<int:pk>/', adminapp.products, name='products'),
class ProductsAdminView(ListView):
    model = Product
    # cat = ProductCategory.objects.filter(pk=pk)
    # products = Product.objects.filter(category_id=cat) 
    # queryset = get_object_or_404(Product, pk=pk)  
    # cat = get_object_or_404(ProductCategory, pk=pk)
    template_name = 'adminapp/product/products.html'
    
    @method_decorator(superuser_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    def get_category(self):
        return ProductCategory.objects.get(pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'this category products'
        cat = self.get_category(**kwargs)
        context['category'] = self.get_category(**kwargs)
        products = Product.objects.filter(category=cat.pk)
        context['object_list'] = products
        # import pdb; pdb.set_trace()
        return context


@superuser_required
def product_read(request):
    pass
# DetailedView

# path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
class ProductReadAdminView(DetailView):
    model = Product
    template_name = 'adminapp/product/product.html'
 
    # @method_decorator(superuser_required)
    # def dispatch(self, request, *args, **kwargs):
    #     return super().dispatch(request, *args, **kwargs)
    def get_cotext_data(self, **kwargs):
        # в inc_categories_menu.html не увидел категории товара, а только all
        # поэтому пытаюсь переопределить контекст с передачей ему категории
        context = super().get_context_data(**kwargs)
        context['categories'] = ProductCategory.objects.all().filter(pk=self.kwargs['pk'])
        return context


# UpdateView
class ProductUpdateAdminView(UpdateView):
    model = Product
    template_name = 'adminapp/product/edit.html'
    fields = '__all__'
    success_url = reverse_lazy('adminapp:products')

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['category'] = ProductCategory.objects.get(pk=self.kwargs['pk'])
    #     return context

def product_delete(request, pk):
    pass
# DeleteView

class ProductDeleteAdminView(DeleteView):
    model = Product
    template_name = 'adminapp/product/delete.html'
    success_url = 'adminapp:products'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'delete prod'
        return context

adminapp/views/user.py
# from django.shortcuts import HttpResponseRedirect
# from django.contrib.auth.decorators import login_required
# from django.contrib.auth.decorators import user_passes_test
from django.http.response import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from authapp.forms import ShopUserRegisterForm, ShopUserEditForm
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator
from authapp.models import ShopUser
from adminapp.utils import superuser_required
from adminapp.forms import ShopUserEditAdminForm, ShopUserCreateAdminForm
from django.core.paginator import Paginator


class UserCreateView(CreateView):
    model = ShopUser
    template_name = 'adminapp/user/edit_u.html'
    form_class = ShopUserCreateAdminForm
    success_url = reverse_lazy("adminapp:users")
    # fields = '__all__'

    @method_decorator(superuser_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'creation of user'
        return context


class UserListView(ListView):
    model = ShopUser
    template_name = 'adminapp/user/users.html'
    #default tamplate name is modelName_list
    paginate_by = 1
    # pg = Paginator(ShopUser.objects.all())

    @method_decorator(superuser_required)
    def dispatch(self, request, *args, **kwargs):  # http.HttpRequest, *args: Any, **kwargs: Any) -> HttpResponseBase:
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'list of users'
        return context    


class UserUpdateView(UpdateView):
    model = ShopUser
    template_name = 'adminapp/user/edit_u.html'
    form_class = ShopUserEditAdminForm
    success_url = reverse_lazy("adminapp:users")
    # fields = '__all__'

    @method_decorator(superuser_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    # def get_object(self, queryset):
    #     # return super().get_object(queryset)
    #     return queryset.get(pk=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'user_editing'
        return context


class UserDeleteView(DeleteView):
    model = ShopUser
    template_name = 'adminapp/user/delete.html'
    success_url = reverse_lazy("adminapp:users")

    def delete(self, request):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'delete selected user'
        return context

adminapp/templates/adminapp/product/delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
  <div class="user_delete">
    Уверены, что хотите удалить {{ object.name }} 
    {% if object.description %}
      ({{ object.description|title }}</b>
      {% if object.price %}
        {{ object.price|title }}
      {% endif %})
    {% endif %}
    ?
    <form action="{% url 'adminapp:product_delete' object.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'adminapp:products' object.category_id %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

adminapp/templates/adminapp/product/edit.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  {% comment %} <button class="btn btn-round form-control last">
    <a href="{% url 'adminapp:products' category.pk %}">
      to the list of products
    </a>
  </button> {% endcomment %}
{% endblock %}

adminapp/templates/adminapp/product/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block header %}
<div class="hero-white">
	<div class="header clearfix">
		{% include 'mainapp/includes/inc_main_menu.html' %}
	</div>
</div>
{% endblock %}

{% block content %}
<div class="details">

    {% include 'mainapp/includes/inc_categories_menu.html' %}

	<script>
		function clickhandler(event){
			alert('hello');
			console.log('hello');
			let address = event.target.getAttribute('src')
			document.getElementById('bigpic').setAttribute(address)
			// хотел чтобы крупная картинка менялась бы по щелчку
			//не понял, почему не получилось
		}
	</script>

	{% if product %}
	<div class="details-products">
		<div class="details-slider">
			<div class="slider-product">
				{% comment %} <img id='bigpic' src="/static/img/slider1.jpg"> {% endcomment %}
				<img id='bigpic' src="{{ product.image.url }}"  width="570px">
			</div>
			<div class="slider-control">
				{% for pic in pics%}
				<div class="block">
					<a href="#"><img src="{% static "img/"|add:pic.adr %}" alt="" onclick="clickhandler()">
						<div class="text"></div>
					</a>
				</div>
				{% endfor%}
			</div>
		</div>
		
		<div class="description">
			<h3 class="big-bold">{{ hot_product.name }}</h3>
			<h3 class="red">горячее предложение</h3>
			<p class="price">{{ product.price}} <span>руб</span></p>
			<a href="{% url 'basket:add' product.id %}" class="red-button">
				заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
			</a>
			<div class="description-text">
				{{ product.description|linebreaks }}
				{% comment %} <p>Расположитесь комфортно.</p> 
				<p>Отличное качество материалов
					позволит вам это.</p> 
					<p>Различные цвета</p>
					<p>высочайший уровень
						эргономики и прочность.</p> {% endcomment %}
					{% comment %} </div> {% endcomment %}
			</div>
			{% comment %} </div> {% endcomment %}
		</div>
	</div>	
	{% endif %}	
	
</div>
{% endblock %}
		

adminapp/templates/adminapp/product/products.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="products_list">
    <button class="new_product">
      <a href={% url 'adminapp:product_create' category.id %}>
        новый продукт
      </a>
    </button> 
		
    {% for object in object_list %}
      <div class="product_record">
        <img 
          src="/media/{{object.image|default:'products_images/default.jpg'}}"
          width="270px"
          alt="{{ object.name }}">
        <div class="product_name">
          {{ object.name|title }}
        </div>
        <div class="product_actions">
          <button>
            <a href={% url 'adminapp:product_read' object.pk %}>
              подробнее
            </a>
          </button>
          <button>
            <a href={% url 'adminapp:product_update' object.pk %}>
              редактировать
            </a>
          </button>
          <button>
            <a href={% url 'adminapp:product_delete' object.pk %}>
              удалить
            </a>
          </button>
        </div>
        <div class="summary">
          <b>цена</b>
          <p>{{ object.price }} руб</p>
          <b>количество</b>
          <p>{{ object.quantity }}</p>
        </div>
        <div class="product_desc">
          {{ object.short_desc|title }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}